name: Commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: nvm
        name: Read .nvmrc
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"

      - name: Setup node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent

      - name: Check code format
        run: yarn run format:check

      - name: Lint
        run: yarn run nx run-many --target=lint --all

      - name: Build
        run: yarn run nx run-many --target=build --all

      - name: Test
        run: yarn run nx run-many --target=test --all

      - name: E2E
        run: yarn run nx run-many --target=e2e --all
